const DEFAULT_SITE_URL = "https://zdossantos.fr";
const DEFAULT_GOOGLE_SITE_VERIFICATION = "AKgIx9bxdB_uJ7h2DyJmHSRsBguhPl3Kh4SE84DXEu8";

const rawSiteUrl = import.meta.env.PUBLIC_SITE_URL?.trim() || DEFAULT_SITE_URL;

export const siteEnv = {
  siteUrl: rawSiteUrl.replace(/\/+$/, ""),
  googleAnalyticsId: import.meta.env.PUBLIC_GA_ID?.trim(),
  googleSiteVerification:
    import.meta.env.PUBLIC_GOOGLE_SITE_VERIFICATION?.trim() ||
    DEFAULT_GOOGLE_SITE_VERIFICATION,
} as const;

export const siteMetadata = {
  defaultTitle:
    "Zacharie Dos Santos – Développeur Freelance Fullstack à Dijon | Vue.js, React, Next.js, Laravel",
  defaultDescription:
    "Zacharie Dos Santos, développeur web freelance fullstack basé à Dijon. Expert Vue.js, React, Next.js, Laravel et TypeScript. +5 ans d'expérience. Disponible pour vos missions freelance en remote ou sur site. Profil Malt vérifié.",
  defaultOgImage: "/images/profile.webp",
  defaultOgImageAlt: "Zacharie Dos Santos – Développeur Freelance Fullstack à Dijon",
  siteName: "Zacharie Dos Santos – Portfolio Développeur Freelance",
  author: "Zacharie Dos Santos",
  twitterHandle: "@ZacharieDS",
  language: "French",
  locale: "fr_FR",
  themeColor: "#ff6b35",
  keywords: [
    "développeur web Dijon",
    "développeur freelance Dijon",
    "développeur fullstack Dijon",
    "freelance développeur web",
    "mission freelance",
    "Malt",
    "développeur Malt",
    "développeur Laravel Dijon",
    "développeur Vue.js Dijon",
    "développeur React Dijon",
    "développeur Next.js Dijon",
    "ReactJS",
    "NextJS",
    "TypeScript",
    "Zacharie Dos Santos",
    "portfolio développeur",
    "développeur web Bourgogne",
    "freelance développeur web Dijon",
    "web developer Dijon France",
    "disponible en freelance",
    "vuejs",
    "react",
    "laravel",
    "typescript",
    "symfony",
    "wordpress",
    "shopify",
    "node.js",
    "développement web sur mesure",
    "application web",
  ],
  geo: {
    region: "FR-BFC",
    placename: "Dijon, Bourgogne-Franche-Comté",
    position: "47.3220;5.0415",
    icbm: "47.3220, 5.0415",
    latitude: 47.322,
    longitude: 5.0415,
    postalCode: "21000",
    city: "Dijon",
    regionName: "Bourgogne-Franche-Comté",
    country: "FR",
  },
  socialLinks: {
    github: "https://github.com/zdossantos",
    twitter: "https://twitter.com/ZacharieDS",
    malt: "https://www.malt.com/profile/zachariedossantos",
    linkedin: "https://www.linkedin.com/in/zacharie-dos-santos-6106441aa/",
  },
  professional: {
    title: "Développeur Web Fullstack Freelance",
    organizationName: "Indépendant / Freelance",
    serviceName: "Zacharie Dos Santos – Développeur Freelance",
    description:
      "Service de développement web freelance fullstack à Dijon. Création d'applications web sur mesure avec Vue.js, React, Next.js, Laravel, TypeScript. Remote ou sur site.",
    serviceTypes: [
      "Développement web",
      "Développement fullstack",
      "Applications web sur mesure",
      "Freelance",
    ],
    offerCatalogName: "Services de développement web",
    offers: [
      "Développement Vue.js",
      "Développement React / Next.js",
      "Développement Laravel / PHP",
      "Développement TypeScript fullstack",
    ],
    areasServed: ["France", "Remote", "Europe"],
    skills: [
      "Laravel",
      "Vue.js",
      "React",
      "ReactJS",
      "Next.js",
      "TypeScript",
      "Astro",
      "PHP",
      "JavaScript",
      "Node.js",
      "Symfony",
      "WordPress",
      "Shopify",
      "Développement web",
      "Fullstack",
      "Freelance",
      "API REST",
      "Tailwind CSS",
    ],
    email: "zacharie21000@gmail.com",
    nationality: "French",
  },
} as const;
